# site settings
title: Oráculo da Bolsa
subtitle: Previsões de preços de ações
email: schillerbr@gmail.com
description: Previsões de preços das ações da bolsa de valores.
baseurl: /
url: https://www.oraculodabolsa.com.br
author: Luiz Schiller
street_address:
city:
state:
zip_code:
country: Brasil
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/oraculodabolsa
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
